version: '3.7'
services:
    db:
        image: postgres:11
        environment:
            - POSTGRES_DB=deli
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        volumes:
            - ./db/data/postgres:/var/lib/postgresql/data  
    migration:
        build: .
        environment:
            - POSTGRES_DB=deli
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 10; done; python3 manage.py migrate'
        depends_on:
            - db
    web:
        build: .
        environment:
            - POSTGRES_DB=deli
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password

        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 10; done; python3 manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/code
        stdin_open: true
        tty: true
        ports:
            - 8000:8000

        depends_on: 
            - db
            - migration
