# Generated by Django 3.2 on 2021-07-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_transactionmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
