# Generated by Django 3.2 on 2021-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_transactionmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
