# Generated by Django 3.2 on 2021-07-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_transactionmodel_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='timestamp',
            new_name='date_of_transaction',
        ),
    ]
