# Generated by Django 3.2 on 2021-07-29 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0005_rename_timestamp_transactionmodel_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='account_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
