# Generated by Django 3.2 on 2021-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_transactionmodel_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debt', 'debt')], default='credit', max_length=255),
            preserve_default=False,
        ),
    ]
